//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Church Financial System
//  @ File Name : Group.cs
//  @ Date : 06/04/2014
//  @ Author : Andrew Titus, William McDermott, Peter-Jon Williams, Matthew Hall, Cecil White
//
//


public class Group {
	private string Name ;
	private Budget Budget ;
	private ArrayList<User> Users = new ArrayList<User>();
	public void CreateGroup(string name, Budget groupBudget){
	}
	public void DeleteGroup(){
	}
	public void AddUser(User user){
	}
	public void RemoveUser(string userID){
	}
	public bool IsAMember(string userID){
	}
	public void AssignBudget(Budget groupBudget){
	}
	public Budget GetBudget(){
	}
}
