//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Church Financial System
//  @ File Name : Permission.cs
//  @ Date : 06/04/2014
//  @ Author : Andrew Titus, William McDermott, Peter-Jon Williams, Matthew Hall, Cecil White
//
//


public class Permission {
	private string ID ;
	private string Type ;
	private bool Allowed ;
	public void CreatePermission(string type, bool allowed){
	}
	public void DeletePermission(){
	}
	public void SetDetails(string type, bool allowed){
	}
	public void UpdatePermission(bool allowed){
	}
	public bool ValidatePermission(){
	}
}
