//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Church Financial System
//  @ File Name : Role.cs
//  @ Date : 06/04/2014
//  @ Author : Andrew Titus, William McDermott, Peter-Jon Williams, Matthew Hall, Cecil White
//
//


public class Role {
	private string ID ;
	private string Name ;
	private string Description ;
	private ArrayList<User> Users = new ArrayList<User>();
	private ArrayList<Permission> Permissions = new ArrayList<Permission>();
	public void CreateRole(string name, string description){
	}
	public void DeleteRole(){
	}
	public void AddUser(User user){
	}
	public void RemoveUser(string userID){
	}
	public bool IsAMember(string userID){
	}
	public void AddPermission(string permissionID){
	}
	public void RemovePermission(string permissionID){
	}
}
