//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Church Financial System
//  @ File Name : UserProfile.cs
//  @ Date : 06/04/2014
//  @ Author : Andrew Titus, William McDermott, Peter-Jon Williams, Matthew Hall, Cecil White
//
//


public class UserProfile {
	private decimal SallaryAmount ;
	private string PayDay ;
	public void CreateProfile(decimal salaryAmount, string payDay){
	}
	public void DeleteProfile(){
	}
	public void UpdateProfile(decimal salaryAmount, string payDay){
	}
	public decimal GetSalary(){
	}
	public string GetPayday(){
	}
	public decimal CalculateTithe(){
	}
}
