//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Church Financial System
//  @ File Name : User.cs
//  @ Date : 06/04/2014
//  @ Author : Andrew Titus, William McDermott, Peter-Jon Williams, Matthew Hall, Cecil White
//
//


using System.Collections.Generic;
public class User {
	private string ID ;
	private string FullName ;
	private string EmailAddress ;
	private List<Permission> Permissions = new List<Permission>();
	private UserProfile Profile ;


	public void CreateUser(string fullName, string emailAddress){
	}

	public void DeleteUser(string ID){
        this.ID = ID;
	}

	public void UpdateUser(string fullName, string emailAddress){
	}

    public string GetFullName(string ID)
    {
        return "";
	}
    public string GetEmailAddress(string ID)
    {

        return "";
	}
	public void AddPermission(Permission newPermission){
	}


}
