//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Church Financial System
//  @ File Name : Log.cs
//  @ Date : 06/04/2014
//  @ Author : Andrew Titus, William McDermott, Peter-Jon Williams, Matthew Hall, Cecil White
//
//


public class Log {
	private string Name ;
	private string Location ;
	private ArrayList<LogItem> LogItems = new ArrayList<LogItem>();
	public void CreateLog(string name, string location){
	}
	public void AddToLog(LogItem logItem){
	}
	public string ReadLogFile(){
	}
}
