//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Church Financial System
//  @ File Name : Transaction.cs
//  @ Date : 06/04/2014
//  @ Author : Andrew Titus, William McDermott, Peter-Jon Williams, Matthew Hall, Cecil White
//
//


public class Transaction {
	private string ID ;
	private string From ;
	private string To ;
	private decimal Value ;
	private string Type ;
	private string PaymentMethod ;
	private PaymentCard PaymentDetails ;
	private string State ;
	public void CreateTransaction(string from, string to, decimal value, string type, string paymentMethod, PaymentCard paymentDetails){
	}
	public bool ProcessTransaction(ElectronicPayment ePayment){
	}
}
