//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Church Financial System
//  @ File Name : BudgetItem.cs
//  @ Date : 06/04/2014
//  @ Author : Andrew Titus, William McDermott, Peter-Jon Williams, Matthew Hall, Cecil White
//
//


public class BudgetItem {
	private string ID ;
	private string Description ;
	private decimal Value ;
	public void CreateBudgetItem(string description, decimal value){
	}
	public void DeleteBudgetItem(){
	}
	public void UpdateBudgetItem(string description, decimal value){
	}
	public string GetDescription(){
	}
	public decimal GetValue(){
	}
}
