//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Church Financial System
//  @ File Name : Invoice.cs
//  @ Date : 06/04/2014
//  @ Author : Andrew Titus, William McDermott, Peter-Jon Williams, Matthew Hall, Cecil White
//
//


public class Invoice : BudgetItem{
	private string SubmissionDate ;
	private string EntryDate ;
	private string From ;
	private ArrayList<Transaction> InvoiceTransaction = new ArrayList<Transaction>();
	public void CreateInvoice(string submissionDate, string entryDate, string from){
	}
	public void GetInvoice(){
	}
	public void PayInvoice(Transaction invoiceTransaction){
	}
	public void AddInvoiceItem(InvoiceItem newInvoiceItem){
	}
	public void RemoveInvoiceItem(){
	}
	public decimal CalculateTotal(){
	}
}
