//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Church Financial System
//  @ File Name : AuditReport.cs
//  @ Date : 06/04/2014
//  @ Author : Andrew Titus, William McDermott, Peter-Jon Williams, Matthew Hall, Cecil White
//
//


public class AuditReport {
	private string Name ;
	private ArrayList<Transaction> Transactions = new ArrayList<Transaction>();
	public RichText PrintReport(){
	}
	public void GenerateReport(){
	}
}
