//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Church Financial System
//  @ File Name : AuditLogItem.cs
//  @ Date : 06/04/2014
//  @ Author : Andrew Titus, William McDermott, Peter-Jon Williams, Matthew Hall, Cecil White
//
//


public class AuditLogItem : LogItem{
	private string Description ;
	private string PreviousState ;
	private string PostState ;
	public void SetDetails(string description, string previousState, string postState){
	}
}
