//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Church Financial System
//  @ File Name : Budget.cs
//  @ Date : 06/04/2014
//  @ Author : Andrew Titus, William McDermott, Peter-Jon Williams, Matthew Hall, Cecil White
//
//


public class Budget {
	private string ID ;
	private string Description ;
	private ArrayList<BudgetItem> BudgetItems = new ArrayList<BudgetItem>();
	public void CreateBudget(string description){
	}
	public void DeleteBudget(){
	}
	public void AddBudgetItem(BudgetItem budgetItem){
	}
	public void RemoveBudgetItem(string budgetItemID){
	}
	public RichText PrintBudget(){
	}
	public void ApproveBudget(){
	}
	public void RejectBudget(){
	}
	public decimal CalculateTotal(){
	}
}
