//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Church Financial System
//  @ File Name : CreditCard.cs
//  @ Date : 06/04/2014
//  @ Author : Andrew Titus, William McDermott, Peter-Jon Williams, Matthew Hall, Cecil White
//
//


public class CreditCard : PaymentCard{
	private string CVV ;
	private string BillingAddress ;
	public void AddCard(string cardNumber, string ownerFullName, string expirationDate, string cvv, string billingAddress){
	}
	public void UpdateCard(string expirationDate, string cvv, string billingAddress){
	}
	public string GetBillingAddress(){
	}
	public bool ValidateCard(){
	}
}
