//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Church Financial System
//  @ File Name : DebitCard.cs
//  @ Date : 06/04/2014
//  @ Author : Andrew Titus, William McDermott, Peter-Jon Williams, Matthew Hall, Cecil White
//
//


public class DebitCard : PaymentCard{
	private string PIN ;
	public void AddCard(string cardNumber, string ownerFullName, string expirationDate, string pin){
	}
	public void UpdateCard(string pin){
	}
	public bool ValidateCard(){
	}
}
