//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Church Financial System
//  @ File Name : ElectronicPayment.cs
//  @ Date : 06/04/2014
//  @ Author : Andrew Titus, William McDermott, Peter-Jon Williams, Matthew Hall, Cecil White
//
//


public class ElectronicPayment {
	private string Name ;
	private string PaymentGateway ;
	public void CreateElectronicPayment(string name, string paymentGateway){
	}
	public bool ExecuteTransaction(){
	}
	public bool TestGateway(){
	}
}
