//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Church Financial System
//  @ File Name : FundingRequest.cs
//  @ Date : 06/04/2014
//  @ Author : Andrew Titus, William McDermott, Peter-Jon Williams, Matthew Hall, Cecil White
//
//


public class FundingRequest : Request{
	private decimal Value ;
	private string Justification ;
	public void SetDetails(decimal value, string justification){
	}
}
