//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Church Financial System
//  @ File Name : InvoiceItem.cs
//  @ Date : 06/04/2014
//  @ Author : Andrew Titus, William McDermott, Peter-Jon Williams, Matthew Hall, Cecil White
//
//


public class InvoiceItem {
	private string ID ;
	private int Multiple ;
	private string Description ;
	private decimal ItemValue ;
	public void CreateInvoiceItem(int multiple, string description, decimal itemValue){
	}
	public void DeleteInvoiceItem(){
	}
	public int GetNumberOfItems(){
	}
	public string GetDescription(){
	}
	public decimal GetItemValue(){
	}
	public decimal CalculateTotal(){
	}
}
