//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Church Financial System
//  @ File Name : LogItem.cs
//  @ Date : 06/04/2014
//  @ Author : Andrew Titus, William McDermott, Peter-Jon Williams, Matthew Hall, Cecil White
//
//


public class LogItem {
	private string UserID ;
	private string TimeStamp ;
	private string LogLine ;
	public void SetDetails(string userId, string timeStamp, string logLine){
	}
}
