//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Church Financial System
//  @ File Name : PaymentCard.cs
//  @ Date : 06/04/2014
//  @ Author : Andrew Titus, William McDermott, Peter-Jon Williams, Matthew Hall, Cecil White
//
//


public abstract class PaymentCard {
	private string CardNumber ;
	private string OwnerFullName ;
	private string ExpirationDate ;
	public void AddCard(string cardNumber, string ownerFullName, string expirationDate){
	}
	public void UpdateCard(string expirationDate){
	}
	public string GetCardNumber(){
	}
	public string GetOwnerFullName(){
	}
	public Date GetExpirationDate(){
	}
	public void DeleteCard(){
	}
	public bool ValidateCard(){
	}
}
