//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Church Financial System
//  @ File Name : Request.cs
//  @ Date : 06/04/2014
//  @ Author : Andrew Titus, William McDermott, Peter-Jon Williams, Matthew Hall, Cecil White
//
//


public class Request {
	private string ID ;
	private string From ;
	private string To ;
	private string Comment ;
	private string State ;
	public void CreateRequest(string from, string to, string comment){
	}
	public void SubmitRequest(){
	}
	public void CancelRequest(){
	}
	public void ApproveRequest(){
	}
	public void RejectRequest(){
	}
}
