//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Church Financial System
//  @ File Name : SytemLogItem.cs
//  @ Date : 06/04/2014
//  @ Author : Andrew Titus, William McDermott, Peter-Jon Williams, Matthew Hall, Cecil White
//
//


public class SytemLogItem : LogItem{
	private string SystemEventCode ;
	public void SetDetails(string systemEventCode){
	}
}
