//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Church Financial System
//  @ File Name : UserInterface.cs
//  @ Date : 06/04/2014
//  @ Author : Andrew Titus, William McDermott, Peter-Jon Williams, Matthew Hall, Cecil White
//
//


public class UserInterface {
	public void AcceptInput(){
	}
	public void UpdateView(){
	}
	public void DisplayMessage(){
	}
}
